// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnumerationIterator.proto

#ifndef PROTOBUF_EnumerationIterator_2eproto__INCLUDED
#define PROTOBUF_EnumerationIterator_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace RAMCloud {
namespace ProtoBuf {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_EnumerationIterator_2eproto();
void protobuf_AssignDesc_EnumerationIterator_2eproto();
void protobuf_ShutdownFile_EnumerationIterator_2eproto();

class EnumerationIterator;
class EnumerationIterator_Frame;

// ===================================================================

class EnumerationIterator_Frame : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RAMCloud.ProtoBuf.EnumerationIterator.Frame) */ {
 public:
  EnumerationIterator_Frame();
  virtual ~EnumerationIterator_Frame();

  EnumerationIterator_Frame(const EnumerationIterator_Frame& from);

  inline EnumerationIterator_Frame& operator=(const EnumerationIterator_Frame& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EnumerationIterator_Frame& default_instance();

  void Swap(EnumerationIterator_Frame* other);

  // implements Message ----------------------------------------------

  inline EnumerationIterator_Frame* New() const { return New(NULL); }

  EnumerationIterator_Frame* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EnumerationIterator_Frame& from);
  void MergeFrom(const EnumerationIterator_Frame& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(EnumerationIterator_Frame* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 tablet_start_hash = 1;
  bool has_tablet_start_hash() const;
  void clear_tablet_start_hash();
  static const int kTabletStartHashFieldNumber = 1;
  ::google::protobuf::uint64 tablet_start_hash() const;
  void set_tablet_start_hash(::google::protobuf::uint64 value);

  // required uint64 tablet_end_hash = 2;
  bool has_tablet_end_hash() const;
  void clear_tablet_end_hash();
  static const int kTabletEndHashFieldNumber = 2;
  ::google::protobuf::uint64 tablet_end_hash() const;
  void set_tablet_end_hash(::google::protobuf::uint64 value);

  // required uint64 num_buckets = 3;
  bool has_num_buckets() const;
  void clear_num_buckets();
  static const int kNumBucketsFieldNumber = 3;
  ::google::protobuf::uint64 num_buckets() const;
  void set_num_buckets(::google::protobuf::uint64 value);

  // required uint64 bucket_index = 4;
  bool has_bucket_index() const;
  void clear_bucket_index();
  static const int kBucketIndexFieldNumber = 4;
  ::google::protobuf::uint64 bucket_index() const;
  void set_bucket_index(::google::protobuf::uint64 value);

  // required uint64 bucket_next_hash = 5;
  bool has_bucket_next_hash() const;
  void clear_bucket_next_hash();
  static const int kBucketNextHashFieldNumber = 5;
  ::google::protobuf::uint64 bucket_next_hash() const;
  void set_bucket_next_hash(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:RAMCloud.ProtoBuf.EnumerationIterator.Frame)
 private:
  inline void set_has_tablet_start_hash();
  inline void clear_has_tablet_start_hash();
  inline void set_has_tablet_end_hash();
  inline void clear_has_tablet_end_hash();
  inline void set_has_num_buckets();
  inline void clear_has_num_buckets();
  inline void set_has_bucket_index();
  inline void clear_has_bucket_index();
  inline void set_has_bucket_next_hash();
  inline void clear_has_bucket_next_hash();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 tablet_start_hash_;
  ::google::protobuf::uint64 tablet_end_hash_;
  ::google::protobuf::uint64 num_buckets_;
  ::google::protobuf::uint64 bucket_index_;
  ::google::protobuf::uint64 bucket_next_hash_;
  friend void  protobuf_AddDesc_EnumerationIterator_2eproto();
  friend void protobuf_AssignDesc_EnumerationIterator_2eproto();
  friend void protobuf_ShutdownFile_EnumerationIterator_2eproto();

  void InitAsDefaultInstance();
  static EnumerationIterator_Frame* default_instance_;
};
// -------------------------------------------------------------------

class EnumerationIterator : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RAMCloud.ProtoBuf.EnumerationIterator) */ {
 public:
  EnumerationIterator();
  virtual ~EnumerationIterator();

  EnumerationIterator(const EnumerationIterator& from);

  inline EnumerationIterator& operator=(const EnumerationIterator& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EnumerationIterator& default_instance();

  void Swap(EnumerationIterator* other);

  // implements Message ----------------------------------------------

  inline EnumerationIterator* New() const { return New(NULL); }

  EnumerationIterator* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EnumerationIterator& from);
  void MergeFrom(const EnumerationIterator& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(EnumerationIterator* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef EnumerationIterator_Frame Frame;

  // accessors -------------------------------------------------------

  // repeated .RAMCloud.ProtoBuf.EnumerationIterator.Frame frames = 1;
  int frames_size() const;
  void clear_frames();
  static const int kFramesFieldNumber = 1;
  const ::RAMCloud::ProtoBuf::EnumerationIterator_Frame& frames(int index) const;
  ::RAMCloud::ProtoBuf::EnumerationIterator_Frame* mutable_frames(int index);
  ::RAMCloud::ProtoBuf::EnumerationIterator_Frame* add_frames();
  ::google::protobuf::RepeatedPtrField< ::RAMCloud::ProtoBuf::EnumerationIterator_Frame >*
      mutable_frames();
  const ::google::protobuf::RepeatedPtrField< ::RAMCloud::ProtoBuf::EnumerationIterator_Frame >&
      frames() const;

  // @@protoc_insertion_point(class_scope:RAMCloud.ProtoBuf.EnumerationIterator)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::RAMCloud::ProtoBuf::EnumerationIterator_Frame > frames_;
  friend void  protobuf_AddDesc_EnumerationIterator_2eproto();
  friend void protobuf_AssignDesc_EnumerationIterator_2eproto();
  friend void protobuf_ShutdownFile_EnumerationIterator_2eproto();

  void InitAsDefaultInstance();
  static EnumerationIterator* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// EnumerationIterator_Frame

// required uint64 tablet_start_hash = 1;
inline bool EnumerationIterator_Frame::has_tablet_start_hash() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EnumerationIterator_Frame::set_has_tablet_start_hash() {
  _has_bits_[0] |= 0x00000001u;
}
inline void EnumerationIterator_Frame::clear_has_tablet_start_hash() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void EnumerationIterator_Frame::clear_tablet_start_hash() {
  tablet_start_hash_ = GOOGLE_ULONGLONG(0);
  clear_has_tablet_start_hash();
}
inline ::google::protobuf::uint64 EnumerationIterator_Frame::tablet_start_hash() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.EnumerationIterator.Frame.tablet_start_hash)
  return tablet_start_hash_;
}
inline void EnumerationIterator_Frame::set_tablet_start_hash(::google::protobuf::uint64 value) {
  set_has_tablet_start_hash();
  tablet_start_hash_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.EnumerationIterator.Frame.tablet_start_hash)
}

// required uint64 tablet_end_hash = 2;
inline bool EnumerationIterator_Frame::has_tablet_end_hash() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void EnumerationIterator_Frame::set_has_tablet_end_hash() {
  _has_bits_[0] |= 0x00000002u;
}
inline void EnumerationIterator_Frame::clear_has_tablet_end_hash() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void EnumerationIterator_Frame::clear_tablet_end_hash() {
  tablet_end_hash_ = GOOGLE_ULONGLONG(0);
  clear_has_tablet_end_hash();
}
inline ::google::protobuf::uint64 EnumerationIterator_Frame::tablet_end_hash() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.EnumerationIterator.Frame.tablet_end_hash)
  return tablet_end_hash_;
}
inline void EnumerationIterator_Frame::set_tablet_end_hash(::google::protobuf::uint64 value) {
  set_has_tablet_end_hash();
  tablet_end_hash_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.EnumerationIterator.Frame.tablet_end_hash)
}

// required uint64 num_buckets = 3;
inline bool EnumerationIterator_Frame::has_num_buckets() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void EnumerationIterator_Frame::set_has_num_buckets() {
  _has_bits_[0] |= 0x00000004u;
}
inline void EnumerationIterator_Frame::clear_has_num_buckets() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void EnumerationIterator_Frame::clear_num_buckets() {
  num_buckets_ = GOOGLE_ULONGLONG(0);
  clear_has_num_buckets();
}
inline ::google::protobuf::uint64 EnumerationIterator_Frame::num_buckets() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.EnumerationIterator.Frame.num_buckets)
  return num_buckets_;
}
inline void EnumerationIterator_Frame::set_num_buckets(::google::protobuf::uint64 value) {
  set_has_num_buckets();
  num_buckets_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.EnumerationIterator.Frame.num_buckets)
}

// required uint64 bucket_index = 4;
inline bool EnumerationIterator_Frame::has_bucket_index() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void EnumerationIterator_Frame::set_has_bucket_index() {
  _has_bits_[0] |= 0x00000008u;
}
inline void EnumerationIterator_Frame::clear_has_bucket_index() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void EnumerationIterator_Frame::clear_bucket_index() {
  bucket_index_ = GOOGLE_ULONGLONG(0);
  clear_has_bucket_index();
}
inline ::google::protobuf::uint64 EnumerationIterator_Frame::bucket_index() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.EnumerationIterator.Frame.bucket_index)
  return bucket_index_;
}
inline void EnumerationIterator_Frame::set_bucket_index(::google::protobuf::uint64 value) {
  set_has_bucket_index();
  bucket_index_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.EnumerationIterator.Frame.bucket_index)
}

// required uint64 bucket_next_hash = 5;
inline bool EnumerationIterator_Frame::has_bucket_next_hash() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void EnumerationIterator_Frame::set_has_bucket_next_hash() {
  _has_bits_[0] |= 0x00000010u;
}
inline void EnumerationIterator_Frame::clear_has_bucket_next_hash() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void EnumerationIterator_Frame::clear_bucket_next_hash() {
  bucket_next_hash_ = GOOGLE_ULONGLONG(0);
  clear_has_bucket_next_hash();
}
inline ::google::protobuf::uint64 EnumerationIterator_Frame::bucket_next_hash() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.EnumerationIterator.Frame.bucket_next_hash)
  return bucket_next_hash_;
}
inline void EnumerationIterator_Frame::set_bucket_next_hash(::google::protobuf::uint64 value) {
  set_has_bucket_next_hash();
  bucket_next_hash_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.EnumerationIterator.Frame.bucket_next_hash)
}

// -------------------------------------------------------------------

// EnumerationIterator

// repeated .RAMCloud.ProtoBuf.EnumerationIterator.Frame frames = 1;
inline int EnumerationIterator::frames_size() const {
  return frames_.size();
}
inline void EnumerationIterator::clear_frames() {
  frames_.Clear();
}
inline const ::RAMCloud::ProtoBuf::EnumerationIterator_Frame& EnumerationIterator::frames(int index) const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.EnumerationIterator.frames)
  return frames_.Get(index);
}
inline ::RAMCloud::ProtoBuf::EnumerationIterator_Frame* EnumerationIterator::mutable_frames(int index) {
  // @@protoc_insertion_point(field_mutable:RAMCloud.ProtoBuf.EnumerationIterator.frames)
  return frames_.Mutable(index);
}
inline ::RAMCloud::ProtoBuf::EnumerationIterator_Frame* EnumerationIterator::add_frames() {
  // @@protoc_insertion_point(field_add:RAMCloud.ProtoBuf.EnumerationIterator.frames)
  return frames_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::RAMCloud::ProtoBuf::EnumerationIterator_Frame >*
EnumerationIterator::mutable_frames() {
  // @@protoc_insertion_point(field_mutable_list:RAMCloud.ProtoBuf.EnumerationIterator.frames)
  return &frames_;
}
inline const ::google::protobuf::RepeatedPtrField< ::RAMCloud::ProtoBuf::EnumerationIterator_Frame >&
EnumerationIterator::frames() const {
  // @@protoc_insertion_point(field_list:RAMCloud.ProtoBuf.EnumerationIterator.frames)
  return frames_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProtoBuf
}  // namespace RAMCloud

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_EnumerationIterator_2eproto__INCLUDED
// RAMCloud pragma [GCCWARN=0]
