// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerStatistics.proto

#ifndef PROTOBUF_ServerStatistics_2eproto__INCLUDED
#define PROTOBUF_ServerStatistics_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "SpinLockStatistics.pb.h"
// @@protoc_insertion_point(includes)

namespace RAMCloud {
namespace ProtoBuf {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ServerStatistics_2eproto();
void protobuf_AssignDesc_ServerStatistics_2eproto();
void protobuf_ShutdownFile_ServerStatistics_2eproto();

class ServerStatistics;
class ServerStatistics_TabletEntry;

// ===================================================================

class ServerStatistics_TabletEntry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RAMCloud.ProtoBuf.ServerStatistics.TabletEntry) */ {
 public:
  ServerStatistics_TabletEntry();
  virtual ~ServerStatistics_TabletEntry();

  ServerStatistics_TabletEntry(const ServerStatistics_TabletEntry& from);

  inline ServerStatistics_TabletEntry& operator=(const ServerStatistics_TabletEntry& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerStatistics_TabletEntry& default_instance();

  void Swap(ServerStatistics_TabletEntry* other);

  // implements Message ----------------------------------------------

  inline ServerStatistics_TabletEntry* New() const { return New(NULL); }

  ServerStatistics_TabletEntry* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerStatistics_TabletEntry& from);
  void MergeFrom(const ServerStatistics_TabletEntry& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ServerStatistics_TabletEntry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 table_id = 1;
  bool has_table_id() const;
  void clear_table_id();
  static const int kTableIdFieldNumber = 1;
  ::google::protobuf::uint64 table_id() const;
  void set_table_id(::google::protobuf::uint64 value);

  // required uint64 start_key_hash = 2;
  bool has_start_key_hash() const;
  void clear_start_key_hash();
  static const int kStartKeyHashFieldNumber = 2;
  ::google::protobuf::uint64 start_key_hash() const;
  void set_start_key_hash(::google::protobuf::uint64 value);

  // required uint64 end_key_hash = 3;
  bool has_end_key_hash() const;
  void clear_end_key_hash();
  static const int kEndKeyHashFieldNumber = 3;
  ::google::protobuf::uint64 end_key_hash() const;
  void set_end_key_hash(::google::protobuf::uint64 value);

  // optional uint64 number_read_and_writes = 4 [default = 0];
  bool has_number_read_and_writes() const;
  void clear_number_read_and_writes();
  static const int kNumberReadAndWritesFieldNumber = 4;
  ::google::protobuf::uint64 number_read_and_writes() const;
  void set_number_read_and_writes(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:RAMCloud.ProtoBuf.ServerStatistics.TabletEntry)
 private:
  inline void set_has_table_id();
  inline void clear_has_table_id();
  inline void set_has_start_key_hash();
  inline void clear_has_start_key_hash();
  inline void set_has_end_key_hash();
  inline void clear_has_end_key_hash();
  inline void set_has_number_read_and_writes();
  inline void clear_has_number_read_and_writes();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 table_id_;
  ::google::protobuf::uint64 start_key_hash_;
  ::google::protobuf::uint64 end_key_hash_;
  ::google::protobuf::uint64 number_read_and_writes_;
  friend void  protobuf_AddDesc_ServerStatistics_2eproto();
  friend void protobuf_AssignDesc_ServerStatistics_2eproto();
  friend void protobuf_ShutdownFile_ServerStatistics_2eproto();

  void InitAsDefaultInstance();
  static ServerStatistics_TabletEntry* default_instance_;
};
// -------------------------------------------------------------------

class ServerStatistics : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RAMCloud.ProtoBuf.ServerStatistics) */ {
 public:
  ServerStatistics();
  virtual ~ServerStatistics();

  ServerStatistics(const ServerStatistics& from);

  inline ServerStatistics& operator=(const ServerStatistics& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerStatistics& default_instance();

  void Swap(ServerStatistics* other);

  // implements Message ----------------------------------------------

  inline ServerStatistics* New() const { return New(NULL); }

  ServerStatistics* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerStatistics& from);
  void MergeFrom(const ServerStatistics& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ServerStatistics* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ServerStatistics_TabletEntry TabletEntry;

  // accessors -------------------------------------------------------

  // repeated .RAMCloud.ProtoBuf.ServerStatistics.TabletEntry tabletentry = 1;
  int tabletentry_size() const;
  void clear_tabletentry();
  static const int kTabletentryFieldNumber = 1;
  const ::RAMCloud::ProtoBuf::ServerStatistics_TabletEntry& tabletentry(int index) const;
  ::RAMCloud::ProtoBuf::ServerStatistics_TabletEntry* mutable_tabletentry(int index);
  ::RAMCloud::ProtoBuf::ServerStatistics_TabletEntry* add_tabletentry();
  ::google::protobuf::RepeatedPtrField< ::RAMCloud::ProtoBuf::ServerStatistics_TabletEntry >*
      mutable_tabletentry();
  const ::google::protobuf::RepeatedPtrField< ::RAMCloud::ProtoBuf::ServerStatistics_TabletEntry >&
      tabletentry() const;

  // required .RAMCloud.ProtoBuf.SpinLockStatistics spin_lock_stats = 2;
  bool has_spin_lock_stats() const;
  void clear_spin_lock_stats();
  static const int kSpinLockStatsFieldNumber = 2;
  const ::RAMCloud::ProtoBuf::SpinLockStatistics& spin_lock_stats() const;
  ::RAMCloud::ProtoBuf::SpinLockStatistics* mutable_spin_lock_stats();
  ::RAMCloud::ProtoBuf::SpinLockStatistics* release_spin_lock_stats();
  void set_allocated_spin_lock_stats(::RAMCloud::ProtoBuf::SpinLockStatistics* spin_lock_stats);

  // @@protoc_insertion_point(class_scope:RAMCloud.ProtoBuf.ServerStatistics)
 private:
  inline void set_has_spin_lock_stats();
  inline void clear_has_spin_lock_stats();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::RAMCloud::ProtoBuf::ServerStatistics_TabletEntry > tabletentry_;
  ::RAMCloud::ProtoBuf::SpinLockStatistics* spin_lock_stats_;
  friend void  protobuf_AddDesc_ServerStatistics_2eproto();
  friend void protobuf_AssignDesc_ServerStatistics_2eproto();
  friend void protobuf_ShutdownFile_ServerStatistics_2eproto();

  void InitAsDefaultInstance();
  static ServerStatistics* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ServerStatistics_TabletEntry

// required uint64 table_id = 1;
inline bool ServerStatistics_TabletEntry::has_table_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ServerStatistics_TabletEntry::set_has_table_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ServerStatistics_TabletEntry::clear_has_table_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ServerStatistics_TabletEntry::clear_table_id() {
  table_id_ = GOOGLE_ULONGLONG(0);
  clear_has_table_id();
}
inline ::google::protobuf::uint64 ServerStatistics_TabletEntry::table_id() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.ServerStatistics.TabletEntry.table_id)
  return table_id_;
}
inline void ServerStatistics_TabletEntry::set_table_id(::google::protobuf::uint64 value) {
  set_has_table_id();
  table_id_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.ServerStatistics.TabletEntry.table_id)
}

// required uint64 start_key_hash = 2;
inline bool ServerStatistics_TabletEntry::has_start_key_hash() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ServerStatistics_TabletEntry::set_has_start_key_hash() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ServerStatistics_TabletEntry::clear_has_start_key_hash() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ServerStatistics_TabletEntry::clear_start_key_hash() {
  start_key_hash_ = GOOGLE_ULONGLONG(0);
  clear_has_start_key_hash();
}
inline ::google::protobuf::uint64 ServerStatistics_TabletEntry::start_key_hash() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.ServerStatistics.TabletEntry.start_key_hash)
  return start_key_hash_;
}
inline void ServerStatistics_TabletEntry::set_start_key_hash(::google::protobuf::uint64 value) {
  set_has_start_key_hash();
  start_key_hash_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.ServerStatistics.TabletEntry.start_key_hash)
}

// required uint64 end_key_hash = 3;
inline bool ServerStatistics_TabletEntry::has_end_key_hash() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ServerStatistics_TabletEntry::set_has_end_key_hash() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ServerStatistics_TabletEntry::clear_has_end_key_hash() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ServerStatistics_TabletEntry::clear_end_key_hash() {
  end_key_hash_ = GOOGLE_ULONGLONG(0);
  clear_has_end_key_hash();
}
inline ::google::protobuf::uint64 ServerStatistics_TabletEntry::end_key_hash() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.ServerStatistics.TabletEntry.end_key_hash)
  return end_key_hash_;
}
inline void ServerStatistics_TabletEntry::set_end_key_hash(::google::protobuf::uint64 value) {
  set_has_end_key_hash();
  end_key_hash_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.ServerStatistics.TabletEntry.end_key_hash)
}

// optional uint64 number_read_and_writes = 4 [default = 0];
inline bool ServerStatistics_TabletEntry::has_number_read_and_writes() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ServerStatistics_TabletEntry::set_has_number_read_and_writes() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ServerStatistics_TabletEntry::clear_has_number_read_and_writes() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ServerStatistics_TabletEntry::clear_number_read_and_writes() {
  number_read_and_writes_ = GOOGLE_ULONGLONG(0);
  clear_has_number_read_and_writes();
}
inline ::google::protobuf::uint64 ServerStatistics_TabletEntry::number_read_and_writes() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.ServerStatistics.TabletEntry.number_read_and_writes)
  return number_read_and_writes_;
}
inline void ServerStatistics_TabletEntry::set_number_read_and_writes(::google::protobuf::uint64 value) {
  set_has_number_read_and_writes();
  number_read_and_writes_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.ServerStatistics.TabletEntry.number_read_and_writes)
}

// -------------------------------------------------------------------

// ServerStatistics

// repeated .RAMCloud.ProtoBuf.ServerStatistics.TabletEntry tabletentry = 1;
inline int ServerStatistics::tabletentry_size() const {
  return tabletentry_.size();
}
inline void ServerStatistics::clear_tabletentry() {
  tabletentry_.Clear();
}
inline const ::RAMCloud::ProtoBuf::ServerStatistics_TabletEntry& ServerStatistics::tabletentry(int index) const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.ServerStatistics.tabletentry)
  return tabletentry_.Get(index);
}
inline ::RAMCloud::ProtoBuf::ServerStatistics_TabletEntry* ServerStatistics::mutable_tabletentry(int index) {
  // @@protoc_insertion_point(field_mutable:RAMCloud.ProtoBuf.ServerStatistics.tabletentry)
  return tabletentry_.Mutable(index);
}
inline ::RAMCloud::ProtoBuf::ServerStatistics_TabletEntry* ServerStatistics::add_tabletentry() {
  // @@protoc_insertion_point(field_add:RAMCloud.ProtoBuf.ServerStatistics.tabletentry)
  return tabletentry_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::RAMCloud::ProtoBuf::ServerStatistics_TabletEntry >*
ServerStatistics::mutable_tabletentry() {
  // @@protoc_insertion_point(field_mutable_list:RAMCloud.ProtoBuf.ServerStatistics.tabletentry)
  return &tabletentry_;
}
inline const ::google::protobuf::RepeatedPtrField< ::RAMCloud::ProtoBuf::ServerStatistics_TabletEntry >&
ServerStatistics::tabletentry() const {
  // @@protoc_insertion_point(field_list:RAMCloud.ProtoBuf.ServerStatistics.tabletentry)
  return tabletentry_;
}

// required .RAMCloud.ProtoBuf.SpinLockStatistics spin_lock_stats = 2;
inline bool ServerStatistics::has_spin_lock_stats() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ServerStatistics::set_has_spin_lock_stats() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ServerStatistics::clear_has_spin_lock_stats() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ServerStatistics::clear_spin_lock_stats() {
  if (spin_lock_stats_ != NULL) spin_lock_stats_->::RAMCloud::ProtoBuf::SpinLockStatistics::Clear();
  clear_has_spin_lock_stats();
}
inline const ::RAMCloud::ProtoBuf::SpinLockStatistics& ServerStatistics::spin_lock_stats() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.ServerStatistics.spin_lock_stats)
  return spin_lock_stats_ != NULL ? *spin_lock_stats_ : *default_instance_->spin_lock_stats_;
}
inline ::RAMCloud::ProtoBuf::SpinLockStatistics* ServerStatistics::mutable_spin_lock_stats() {
  set_has_spin_lock_stats();
  if (spin_lock_stats_ == NULL) {
    spin_lock_stats_ = new ::RAMCloud::ProtoBuf::SpinLockStatistics;
  }
  // @@protoc_insertion_point(field_mutable:RAMCloud.ProtoBuf.ServerStatistics.spin_lock_stats)
  return spin_lock_stats_;
}
inline ::RAMCloud::ProtoBuf::SpinLockStatistics* ServerStatistics::release_spin_lock_stats() {
  // @@protoc_insertion_point(field_release:RAMCloud.ProtoBuf.ServerStatistics.spin_lock_stats)
  clear_has_spin_lock_stats();
  ::RAMCloud::ProtoBuf::SpinLockStatistics* temp = spin_lock_stats_;
  spin_lock_stats_ = NULL;
  return temp;
}
inline void ServerStatistics::set_allocated_spin_lock_stats(::RAMCloud::ProtoBuf::SpinLockStatistics* spin_lock_stats) {
  delete spin_lock_stats_;
  spin_lock_stats_ = spin_lock_stats;
  if (spin_lock_stats) {
    set_has_spin_lock_stats();
  } else {
    clear_has_spin_lock_stats();
  }
  // @@protoc_insertion_point(field_set_allocated:RAMCloud.ProtoBuf.ServerStatistics.spin_lock_stats)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProtoBuf
}  // namespace RAMCloud

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ServerStatistics_2eproto__INCLUDED
// RAMCloud pragma [GCCWARN=0]
