// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tablets.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Tablets.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace RAMCloud {
namespace ProtoBuf {

namespace {

const ::google::protobuf::Descriptor* Tablets_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Tablets_reflection_ = NULL;
const ::google::protobuf::Descriptor* Tablets_Tablet_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Tablets_Tablet_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* Tablets_Tablet_State_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_Tablets_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_Tablets_2eproto() {
  protobuf_AddDesc_Tablets_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Tablets.proto");
  GOOGLE_CHECK(file != NULL);
  Tablets_descriptor_ = file->message_type(0);
  static const int Tablets_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Tablets, tablet_),
  };
  Tablets_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Tablets_descriptor_,
      Tablets::default_instance_,
      Tablets_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Tablets, _has_bits_[0]),
      -1,
      -1,
      sizeof(Tablets),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Tablets, _internal_metadata_),
      -1);
  Tablets_Tablet_descriptor_ = Tablets_descriptor_->nested_type(0);
  static const int Tablets_Tablet_offsets_[9] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Tablets_Tablet, table_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Tablets_Tablet, start_key_hash_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Tablets_Tablet, end_key_hash_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Tablets_Tablet, state_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Tablets_Tablet, server_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Tablets_Tablet, service_locator_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Tablets_Tablet, user_data_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Tablets_Tablet, ctime_log_head_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Tablets_Tablet, ctime_log_head_offset_),
  };
  Tablets_Tablet_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Tablets_Tablet_descriptor_,
      Tablets_Tablet::default_instance_,
      Tablets_Tablet_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Tablets_Tablet, _has_bits_[0]),
      -1,
      -1,
      sizeof(Tablets_Tablet),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Tablets_Tablet, _internal_metadata_),
      -1);
  Tablets_Tablet_State_descriptor_ = Tablets_Tablet_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Tablets_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Tablets_descriptor_, &Tablets::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Tablets_Tablet_descriptor_, &Tablets_Tablet::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Tablets_2eproto() {
  delete Tablets::default_instance_;
  delete Tablets_reflection_;
  delete Tablets_Tablet::default_instance_;
  delete Tablets_Tablet_reflection_;
}

void protobuf_AddDesc_Tablets_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_Tablets_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rTablets.proto\022\021RAMCloud.ProtoBuf\"\335\002\n\007T"
    "ablets\0221\n\006tablet\030\001 \003(\0132!.RAMCloud.ProtoB"
    "uf.Tablets.Tablet\032\236\002\n\006Tablet\022\020\n\010table_id"
    "\030\001 \002(\004\022\026\n\016start_key_hash\030\002 \002(\004\022\024\n\014end_ke"
    "y_hash\030\003 \002(\004\0226\n\005state\030\004 \002(\0162\'.RAMCloud.P"
    "rotoBuf.Tablets.Tablet.State\022\021\n\tserver_i"
    "d\030\005 \001(\006\022\027\n\017service_locator\030\006 \001(\t\022\021\n\tuser"
    "_data\030\007 \001(\006\022\031\n\021ctime_log_head_id\030\010 \002(\004\022\035"
    "\n\025ctime_log_head_offset\030\t \002(\r\"#\n\005State\022\n"
    "\n\006NORMAL\020\000\022\016\n\nRECOVERING\020\001", 386);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Tablets.proto", &protobuf_RegisterTypes);
  Tablets::default_instance_ = new Tablets();
  Tablets_Tablet::default_instance_ = new Tablets_Tablet();
  Tablets::default_instance_->InitAsDefaultInstance();
  Tablets_Tablet::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Tablets_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Tablets_2eproto {
  StaticDescriptorInitializer_Tablets_2eproto() {
    protobuf_AddDesc_Tablets_2eproto();
  }
} static_descriptor_initializer_Tablets_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* Tablets_Tablet_State_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Tablets_Tablet_State_descriptor_;
}
bool Tablets_Tablet_State_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Tablets_Tablet_State Tablets_Tablet::NORMAL;
const Tablets_Tablet_State Tablets_Tablet::RECOVERING;
const Tablets_Tablet_State Tablets_Tablet::State_MIN;
const Tablets_Tablet_State Tablets_Tablet::State_MAX;
const int Tablets_Tablet::State_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Tablets_Tablet::kTableIdFieldNumber;
const int Tablets_Tablet::kStartKeyHashFieldNumber;
const int Tablets_Tablet::kEndKeyHashFieldNumber;
const int Tablets_Tablet::kStateFieldNumber;
const int Tablets_Tablet::kServerIdFieldNumber;
const int Tablets_Tablet::kServiceLocatorFieldNumber;
const int Tablets_Tablet::kUserDataFieldNumber;
const int Tablets_Tablet::kCtimeLogHeadIdFieldNumber;
const int Tablets_Tablet::kCtimeLogHeadOffsetFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Tablets_Tablet::Tablets_Tablet()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:RAMCloud.ProtoBuf.Tablets.Tablet)
}

void Tablets_Tablet::InitAsDefaultInstance() {
}

Tablets_Tablet::Tablets_Tablet(const Tablets_Tablet& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:RAMCloud.ProtoBuf.Tablets.Tablet)
}

void Tablets_Tablet::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  table_id_ = GOOGLE_ULONGLONG(0);
  start_key_hash_ = GOOGLE_ULONGLONG(0);
  end_key_hash_ = GOOGLE_ULONGLONG(0);
  state_ = 0;
  server_id_ = GOOGLE_ULONGLONG(0);
  service_locator_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  user_data_ = GOOGLE_ULONGLONG(0);
  ctime_log_head_id_ = GOOGLE_ULONGLONG(0);
  ctime_log_head_offset_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Tablets_Tablet::~Tablets_Tablet() {
  // @@protoc_insertion_point(destructor:RAMCloud.ProtoBuf.Tablets.Tablet)
  SharedDtor();
}

void Tablets_Tablet::SharedDtor() {
  service_locator_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Tablets_Tablet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Tablets_Tablet::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Tablets_Tablet_descriptor_;
}

const Tablets_Tablet& Tablets_Tablet::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Tablets_2eproto();
  return *default_instance_;
}

Tablets_Tablet* Tablets_Tablet::default_instance_ = NULL;

Tablets_Tablet* Tablets_Tablet::New(::google::protobuf::Arena* arena) const {
  Tablets_Tablet* n = new Tablets_Tablet;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Tablets_Tablet::Clear() {
// @@protoc_insertion_point(message_clear_start:RAMCloud.ProtoBuf.Tablets.Tablet)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(Tablets_Tablet, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<Tablets_Tablet*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 255u) {
    ZR_(table_id_, server_id_);
    ZR_(user_data_, ctime_log_head_id_);
    state_ = 0;
    if (has_service_locator()) {
      service_locator_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }
  ctime_log_head_offset_ = 0u;

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool Tablets_Tablet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:RAMCloud.ProtoBuf.Tablets.Tablet)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 table_id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &table_id_)));
          set_has_table_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_start_key_hash;
        break;
      }

      // required uint64 start_key_hash = 2;
      case 2: {
        if (tag == 16) {
         parse_start_key_hash:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &start_key_hash_)));
          set_has_start_key_hash();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_end_key_hash;
        break;
      }

      // required uint64 end_key_hash = 3;
      case 3: {
        if (tag == 24) {
         parse_end_key_hash:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &end_key_hash_)));
          set_has_end_key_hash();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_state;
        break;
      }

      // required .RAMCloud.ProtoBuf.Tablets.Tablet.State state = 4;
      case 4: {
        if (tag == 32) {
         parse_state:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::RAMCloud::ProtoBuf::Tablets_Tablet_State_IsValid(value)) {
            set_state(static_cast< ::RAMCloud::ProtoBuf::Tablets_Tablet_State >(value));
          } else {
            mutable_unknown_fields()->AddVarint(4, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(41)) goto parse_server_id;
        break;
      }

      // optional fixed64 server_id = 5;
      case 5: {
        if (tag == 41) {
         parse_server_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED64>(
                 input, &server_id_)));
          set_has_server_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_service_locator;
        break;
      }

      // optional string service_locator = 6;
      case 6: {
        if (tag == 50) {
         parse_service_locator:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_service_locator()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->service_locator().data(), this->service_locator().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "RAMCloud.ProtoBuf.Tablets.Tablet.service_locator");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(57)) goto parse_user_data;
        break;
      }

      // optional fixed64 user_data = 7;
      case 7: {
        if (tag == 57) {
         parse_user_data:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED64>(
                 input, &user_data_)));
          set_has_user_data();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_ctime_log_head_id;
        break;
      }

      // required uint64 ctime_log_head_id = 8;
      case 8: {
        if (tag == 64) {
         parse_ctime_log_head_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &ctime_log_head_id_)));
          set_has_ctime_log_head_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(72)) goto parse_ctime_log_head_offset;
        break;
      }

      // required uint32 ctime_log_head_offset = 9;
      case 9: {
        if (tag == 72) {
         parse_ctime_log_head_offset:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &ctime_log_head_offset_)));
          set_has_ctime_log_head_offset();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:RAMCloud.ProtoBuf.Tablets.Tablet)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:RAMCloud.ProtoBuf.Tablets.Tablet)
  return false;
#undef DO_
}

void Tablets_Tablet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:RAMCloud.ProtoBuf.Tablets.Tablet)
  // required uint64 table_id = 1;
  if (has_table_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->table_id(), output);
  }

  // required uint64 start_key_hash = 2;
  if (has_start_key_hash()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->start_key_hash(), output);
  }

  // required uint64 end_key_hash = 3;
  if (has_end_key_hash()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->end_key_hash(), output);
  }

  // required .RAMCloud.ProtoBuf.Tablets.Tablet.State state = 4;
  if (has_state()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->state(), output);
  }

  // optional fixed64 server_id = 5;
  if (has_server_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed64(5, this->server_id(), output);
  }

  // optional string service_locator = 6;
  if (has_service_locator()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->service_locator().data(), this->service_locator().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "RAMCloud.ProtoBuf.Tablets.Tablet.service_locator");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->service_locator(), output);
  }

  // optional fixed64 user_data = 7;
  if (has_user_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed64(7, this->user_data(), output);
  }

  // required uint64 ctime_log_head_id = 8;
  if (has_ctime_log_head_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(8, this->ctime_log_head_id(), output);
  }

  // required uint32 ctime_log_head_offset = 9;
  if (has_ctime_log_head_offset()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(9, this->ctime_log_head_offset(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:RAMCloud.ProtoBuf.Tablets.Tablet)
}

::google::protobuf::uint8* Tablets_Tablet::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:RAMCloud.ProtoBuf.Tablets.Tablet)
  // required uint64 table_id = 1;
  if (has_table_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->table_id(), target);
  }

  // required uint64 start_key_hash = 2;
  if (has_start_key_hash()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->start_key_hash(), target);
  }

  // required uint64 end_key_hash = 3;
  if (has_end_key_hash()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->end_key_hash(), target);
  }

  // required .RAMCloud.ProtoBuf.Tablets.Tablet.State state = 4;
  if (has_state()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      4, this->state(), target);
  }

  // optional fixed64 server_id = 5;
  if (has_server_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed64ToArray(5, this->server_id(), target);
  }

  // optional string service_locator = 6;
  if (has_service_locator()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->service_locator().data(), this->service_locator().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "RAMCloud.ProtoBuf.Tablets.Tablet.service_locator");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->service_locator(), target);
  }

  // optional fixed64 user_data = 7;
  if (has_user_data()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed64ToArray(7, this->user_data(), target);
  }

  // required uint64 ctime_log_head_id = 8;
  if (has_ctime_log_head_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(8, this->ctime_log_head_id(), target);
  }

  // required uint32 ctime_log_head_offset = 9;
  if (has_ctime_log_head_offset()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(9, this->ctime_log_head_offset(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RAMCloud.ProtoBuf.Tablets.Tablet)
  return target;
}

int Tablets_Tablet::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:RAMCloud.ProtoBuf.Tablets.Tablet)
  int total_size = 0;

  if (has_table_id()) {
    // required uint64 table_id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->table_id());
  }

  if (has_start_key_hash()) {
    // required uint64 start_key_hash = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->start_key_hash());
  }

  if (has_end_key_hash()) {
    // required uint64 end_key_hash = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->end_key_hash());
  }

  if (has_state()) {
    // required .RAMCloud.ProtoBuf.Tablets.Tablet.State state = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->state());
  }

  if (has_ctime_log_head_id()) {
    // required uint64 ctime_log_head_id = 8;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->ctime_log_head_id());
  }

  if (has_ctime_log_head_offset()) {
    // required uint32 ctime_log_head_offset = 9;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->ctime_log_head_offset());
  }

  return total_size;
}
int Tablets_Tablet::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:RAMCloud.ProtoBuf.Tablets.Tablet)
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000018f) ^ 0x0000018f) == 0) {  // All required fields are present.
    // required uint64 table_id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->table_id());

    // required uint64 start_key_hash = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->start_key_hash());

    // required uint64 end_key_hash = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->end_key_hash());

    // required .RAMCloud.ProtoBuf.Tablets.Tablet.State state = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->state());

    // required uint64 ctime_log_head_id = 8;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->ctime_log_head_id());

    // required uint32 ctime_log_head_offset = 9;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->ctime_log_head_offset());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_has_bits_[4 / 32] & 112u) {
    // optional fixed64 server_id = 5;
    if (has_server_id()) {
      total_size += 1 + 8;
    }

    // optional string service_locator = 6;
    if (has_service_locator()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->service_locator());
    }

    // optional fixed64 user_data = 7;
    if (has_user_data()) {
      total_size += 1 + 8;
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Tablets_Tablet::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:RAMCloud.ProtoBuf.Tablets.Tablet)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Tablets_Tablet* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Tablets_Tablet>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:RAMCloud.ProtoBuf.Tablets.Tablet)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:RAMCloud.ProtoBuf.Tablets.Tablet)
    MergeFrom(*source);
  }
}

void Tablets_Tablet::MergeFrom(const Tablets_Tablet& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:RAMCloud.ProtoBuf.Tablets.Tablet)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_table_id()) {
      set_table_id(from.table_id());
    }
    if (from.has_start_key_hash()) {
      set_start_key_hash(from.start_key_hash());
    }
    if (from.has_end_key_hash()) {
      set_end_key_hash(from.end_key_hash());
    }
    if (from.has_state()) {
      set_state(from.state());
    }
    if (from.has_server_id()) {
      set_server_id(from.server_id());
    }
    if (from.has_service_locator()) {
      set_has_service_locator();
      service_locator_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.service_locator_);
    }
    if (from.has_user_data()) {
      set_user_data(from.user_data());
    }
    if (from.has_ctime_log_head_id()) {
      set_ctime_log_head_id(from.ctime_log_head_id());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_ctime_log_head_offset()) {
      set_ctime_log_head_offset(from.ctime_log_head_offset());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void Tablets_Tablet::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:RAMCloud.ProtoBuf.Tablets.Tablet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Tablets_Tablet::CopyFrom(const Tablets_Tablet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RAMCloud.ProtoBuf.Tablets.Tablet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Tablets_Tablet::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000018f) != 0x0000018f) return false;

  return true;
}

void Tablets_Tablet::Swap(Tablets_Tablet* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Tablets_Tablet::InternalSwap(Tablets_Tablet* other) {
  std::swap(table_id_, other->table_id_);
  std::swap(start_key_hash_, other->start_key_hash_);
  std::swap(end_key_hash_, other->end_key_hash_);
  std::swap(state_, other->state_);
  std::swap(server_id_, other->server_id_);
  service_locator_.Swap(&other->service_locator_);
  std::swap(user_data_, other->user_data_);
  std::swap(ctime_log_head_id_, other->ctime_log_head_id_);
  std::swap(ctime_log_head_offset_, other->ctime_log_head_offset_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Tablets_Tablet::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Tablets_Tablet_descriptor_;
  metadata.reflection = Tablets_Tablet_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Tablets::kTabletFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Tablets::Tablets()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:RAMCloud.ProtoBuf.Tablets)
}

void Tablets::InitAsDefaultInstance() {
}

Tablets::Tablets(const Tablets& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:RAMCloud.ProtoBuf.Tablets)
}

void Tablets::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Tablets::~Tablets() {
  // @@protoc_insertion_point(destructor:RAMCloud.ProtoBuf.Tablets)
  SharedDtor();
}

void Tablets::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Tablets::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Tablets::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Tablets_descriptor_;
}

const Tablets& Tablets::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Tablets_2eproto();
  return *default_instance_;
}

Tablets* Tablets::default_instance_ = NULL;

Tablets* Tablets::New(::google::protobuf::Arena* arena) const {
  Tablets* n = new Tablets;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Tablets::Clear() {
// @@protoc_insertion_point(message_clear_start:RAMCloud.ProtoBuf.Tablets)
  tablet_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool Tablets::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:RAMCloud.ProtoBuf.Tablets)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .RAMCloud.ProtoBuf.Tablets.Tablet tablet = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_tablet:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_tablet()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_tablet;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:RAMCloud.ProtoBuf.Tablets)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:RAMCloud.ProtoBuf.Tablets)
  return false;
#undef DO_
}

void Tablets::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:RAMCloud.ProtoBuf.Tablets)
  // repeated .RAMCloud.ProtoBuf.Tablets.Tablet tablet = 1;
  for (unsigned int i = 0, n = this->tablet_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->tablet(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:RAMCloud.ProtoBuf.Tablets)
}

::google::protobuf::uint8* Tablets::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:RAMCloud.ProtoBuf.Tablets)
  // repeated .RAMCloud.ProtoBuf.Tablets.Tablet tablet = 1;
  for (unsigned int i = 0, n = this->tablet_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->tablet(i), false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RAMCloud.ProtoBuf.Tablets)
  return target;
}

int Tablets::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:RAMCloud.ProtoBuf.Tablets)
  int total_size = 0;

  // repeated .RAMCloud.ProtoBuf.Tablets.Tablet tablet = 1;
  total_size += 1 * this->tablet_size();
  for (int i = 0; i < this->tablet_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->tablet(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Tablets::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:RAMCloud.ProtoBuf.Tablets)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Tablets* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Tablets>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:RAMCloud.ProtoBuf.Tablets)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:RAMCloud.ProtoBuf.Tablets)
    MergeFrom(*source);
  }
}

void Tablets::MergeFrom(const Tablets& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:RAMCloud.ProtoBuf.Tablets)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  tablet_.MergeFrom(from.tablet_);
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void Tablets::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:RAMCloud.ProtoBuf.Tablets)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Tablets::CopyFrom(const Tablets& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RAMCloud.ProtoBuf.Tablets)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Tablets::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->tablet())) return false;
  return true;
}

void Tablets::Swap(Tablets* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Tablets::InternalSwap(Tablets* other) {
  tablet_.UnsafeArenaSwap(&other->tablet_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Tablets::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Tablets_descriptor_;
  metadata.reflection = Tablets_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Tablets_Tablet

// required uint64 table_id = 1;
bool Tablets_Tablet::has_table_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Tablets_Tablet::set_has_table_id() {
  _has_bits_[0] |= 0x00000001u;
}
void Tablets_Tablet::clear_has_table_id() {
  _has_bits_[0] &= ~0x00000001u;
}
void Tablets_Tablet::clear_table_id() {
  table_id_ = GOOGLE_ULONGLONG(0);
  clear_has_table_id();
}
 ::google::protobuf::uint64 Tablets_Tablet::table_id() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.Tablets.Tablet.table_id)
  return table_id_;
}
 void Tablets_Tablet::set_table_id(::google::protobuf::uint64 value) {
  set_has_table_id();
  table_id_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.Tablets.Tablet.table_id)
}

// required uint64 start_key_hash = 2;
bool Tablets_Tablet::has_start_key_hash() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void Tablets_Tablet::set_has_start_key_hash() {
  _has_bits_[0] |= 0x00000002u;
}
void Tablets_Tablet::clear_has_start_key_hash() {
  _has_bits_[0] &= ~0x00000002u;
}
void Tablets_Tablet::clear_start_key_hash() {
  start_key_hash_ = GOOGLE_ULONGLONG(0);
  clear_has_start_key_hash();
}
 ::google::protobuf::uint64 Tablets_Tablet::start_key_hash() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.Tablets.Tablet.start_key_hash)
  return start_key_hash_;
}
 void Tablets_Tablet::set_start_key_hash(::google::protobuf::uint64 value) {
  set_has_start_key_hash();
  start_key_hash_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.Tablets.Tablet.start_key_hash)
}

// required uint64 end_key_hash = 3;
bool Tablets_Tablet::has_end_key_hash() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void Tablets_Tablet::set_has_end_key_hash() {
  _has_bits_[0] |= 0x00000004u;
}
void Tablets_Tablet::clear_has_end_key_hash() {
  _has_bits_[0] &= ~0x00000004u;
}
void Tablets_Tablet::clear_end_key_hash() {
  end_key_hash_ = GOOGLE_ULONGLONG(0);
  clear_has_end_key_hash();
}
 ::google::protobuf::uint64 Tablets_Tablet::end_key_hash() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.Tablets.Tablet.end_key_hash)
  return end_key_hash_;
}
 void Tablets_Tablet::set_end_key_hash(::google::protobuf::uint64 value) {
  set_has_end_key_hash();
  end_key_hash_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.Tablets.Tablet.end_key_hash)
}

// required .RAMCloud.ProtoBuf.Tablets.Tablet.State state = 4;
bool Tablets_Tablet::has_state() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void Tablets_Tablet::set_has_state() {
  _has_bits_[0] |= 0x00000008u;
}
void Tablets_Tablet::clear_has_state() {
  _has_bits_[0] &= ~0x00000008u;
}
void Tablets_Tablet::clear_state() {
  state_ = 0;
  clear_has_state();
}
 ::RAMCloud::ProtoBuf::Tablets_Tablet_State Tablets_Tablet::state() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.Tablets.Tablet.state)
  return static_cast< ::RAMCloud::ProtoBuf::Tablets_Tablet_State >(state_);
}
 void Tablets_Tablet::set_state(::RAMCloud::ProtoBuf::Tablets_Tablet_State value) {
  assert(::RAMCloud::ProtoBuf::Tablets_Tablet_State_IsValid(value));
  set_has_state();
  state_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.Tablets.Tablet.state)
}

// optional fixed64 server_id = 5;
bool Tablets_Tablet::has_server_id() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void Tablets_Tablet::set_has_server_id() {
  _has_bits_[0] |= 0x00000010u;
}
void Tablets_Tablet::clear_has_server_id() {
  _has_bits_[0] &= ~0x00000010u;
}
void Tablets_Tablet::clear_server_id() {
  server_id_ = GOOGLE_ULONGLONG(0);
  clear_has_server_id();
}
 ::google::protobuf::uint64 Tablets_Tablet::server_id() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.Tablets.Tablet.server_id)
  return server_id_;
}
 void Tablets_Tablet::set_server_id(::google::protobuf::uint64 value) {
  set_has_server_id();
  server_id_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.Tablets.Tablet.server_id)
}

// optional string service_locator = 6;
bool Tablets_Tablet::has_service_locator() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void Tablets_Tablet::set_has_service_locator() {
  _has_bits_[0] |= 0x00000020u;
}
void Tablets_Tablet::clear_has_service_locator() {
  _has_bits_[0] &= ~0x00000020u;
}
void Tablets_Tablet::clear_service_locator() {
  service_locator_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_service_locator();
}
 const ::std::string& Tablets_Tablet::service_locator() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.Tablets.Tablet.service_locator)
  return service_locator_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Tablets_Tablet::set_service_locator(const ::std::string& value) {
  set_has_service_locator();
  service_locator_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.Tablets.Tablet.service_locator)
}
 void Tablets_Tablet::set_service_locator(const char* value) {
  set_has_service_locator();
  service_locator_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RAMCloud.ProtoBuf.Tablets.Tablet.service_locator)
}
 void Tablets_Tablet::set_service_locator(const char* value, size_t size) {
  set_has_service_locator();
  service_locator_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RAMCloud.ProtoBuf.Tablets.Tablet.service_locator)
}
 ::std::string* Tablets_Tablet::mutable_service_locator() {
  set_has_service_locator();
  // @@protoc_insertion_point(field_mutable:RAMCloud.ProtoBuf.Tablets.Tablet.service_locator)
  return service_locator_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Tablets_Tablet::release_service_locator() {
  // @@protoc_insertion_point(field_release:RAMCloud.ProtoBuf.Tablets.Tablet.service_locator)
  clear_has_service_locator();
  return service_locator_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Tablets_Tablet::set_allocated_service_locator(::std::string* service_locator) {
  if (service_locator != NULL) {
    set_has_service_locator();
  } else {
    clear_has_service_locator();
  }
  service_locator_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), service_locator);
  // @@protoc_insertion_point(field_set_allocated:RAMCloud.ProtoBuf.Tablets.Tablet.service_locator)
}

// optional fixed64 user_data = 7;
bool Tablets_Tablet::has_user_data() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
void Tablets_Tablet::set_has_user_data() {
  _has_bits_[0] |= 0x00000040u;
}
void Tablets_Tablet::clear_has_user_data() {
  _has_bits_[0] &= ~0x00000040u;
}
void Tablets_Tablet::clear_user_data() {
  user_data_ = GOOGLE_ULONGLONG(0);
  clear_has_user_data();
}
 ::google::protobuf::uint64 Tablets_Tablet::user_data() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.Tablets.Tablet.user_data)
  return user_data_;
}
 void Tablets_Tablet::set_user_data(::google::protobuf::uint64 value) {
  set_has_user_data();
  user_data_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.Tablets.Tablet.user_data)
}

// required uint64 ctime_log_head_id = 8;
bool Tablets_Tablet::has_ctime_log_head_id() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
void Tablets_Tablet::set_has_ctime_log_head_id() {
  _has_bits_[0] |= 0x00000080u;
}
void Tablets_Tablet::clear_has_ctime_log_head_id() {
  _has_bits_[0] &= ~0x00000080u;
}
void Tablets_Tablet::clear_ctime_log_head_id() {
  ctime_log_head_id_ = GOOGLE_ULONGLONG(0);
  clear_has_ctime_log_head_id();
}
 ::google::protobuf::uint64 Tablets_Tablet::ctime_log_head_id() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.Tablets.Tablet.ctime_log_head_id)
  return ctime_log_head_id_;
}
 void Tablets_Tablet::set_ctime_log_head_id(::google::protobuf::uint64 value) {
  set_has_ctime_log_head_id();
  ctime_log_head_id_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.Tablets.Tablet.ctime_log_head_id)
}

// required uint32 ctime_log_head_offset = 9;
bool Tablets_Tablet::has_ctime_log_head_offset() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
void Tablets_Tablet::set_has_ctime_log_head_offset() {
  _has_bits_[0] |= 0x00000100u;
}
void Tablets_Tablet::clear_has_ctime_log_head_offset() {
  _has_bits_[0] &= ~0x00000100u;
}
void Tablets_Tablet::clear_ctime_log_head_offset() {
  ctime_log_head_offset_ = 0u;
  clear_has_ctime_log_head_offset();
}
 ::google::protobuf::uint32 Tablets_Tablet::ctime_log_head_offset() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.Tablets.Tablet.ctime_log_head_offset)
  return ctime_log_head_offset_;
}
 void Tablets_Tablet::set_ctime_log_head_offset(::google::protobuf::uint32 value) {
  set_has_ctime_log_head_offset();
  ctime_log_head_offset_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.Tablets.Tablet.ctime_log_head_offset)
}

// -------------------------------------------------------------------

// Tablets

// repeated .RAMCloud.ProtoBuf.Tablets.Tablet tablet = 1;
int Tablets::tablet_size() const {
  return tablet_.size();
}
void Tablets::clear_tablet() {
  tablet_.Clear();
}
const ::RAMCloud::ProtoBuf::Tablets_Tablet& Tablets::tablet(int index) const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.Tablets.tablet)
  return tablet_.Get(index);
}
::RAMCloud::ProtoBuf::Tablets_Tablet* Tablets::mutable_tablet(int index) {
  // @@protoc_insertion_point(field_mutable:RAMCloud.ProtoBuf.Tablets.tablet)
  return tablet_.Mutable(index);
}
::RAMCloud::ProtoBuf::Tablets_Tablet* Tablets::add_tablet() {
  // @@protoc_insertion_point(field_add:RAMCloud.ProtoBuf.Tablets.tablet)
  return tablet_.Add();
}
::google::protobuf::RepeatedPtrField< ::RAMCloud::ProtoBuf::Tablets_Tablet >*
Tablets::mutable_tablet() {
  // @@protoc_insertion_point(field_mutable_list:RAMCloud.ProtoBuf.Tablets.tablet)
  return &tablet_;
}
const ::google::protobuf::RepeatedPtrField< ::RAMCloud::ProtoBuf::Tablets_Tablet >&
Tablets::tablet() const {
  // @@protoc_insertion_point(field_list:RAMCloud.ProtoBuf.Tablets.tablet)
  return tablet_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace ProtoBuf
}  // namespace RAMCloud

// @@protoc_insertion_point(global_scope)
// RAMCloud pragma [GCCWARN=0]
