// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tablets.proto

#ifndef PROTOBUF_Tablets_2eproto__INCLUDED
#define PROTOBUF_Tablets_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace RAMCloud {
namespace ProtoBuf {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_Tablets_2eproto();
void protobuf_AssignDesc_Tablets_2eproto();
void protobuf_ShutdownFile_Tablets_2eproto();

class Tablets;
class Tablets_Tablet;

enum Tablets_Tablet_State {
  Tablets_Tablet_State_NORMAL = 0,
  Tablets_Tablet_State_RECOVERING = 1
};
bool Tablets_Tablet_State_IsValid(int value);
const Tablets_Tablet_State Tablets_Tablet_State_State_MIN = Tablets_Tablet_State_NORMAL;
const Tablets_Tablet_State Tablets_Tablet_State_State_MAX = Tablets_Tablet_State_RECOVERING;
const int Tablets_Tablet_State_State_ARRAYSIZE = Tablets_Tablet_State_State_MAX + 1;

const ::google::protobuf::EnumDescriptor* Tablets_Tablet_State_descriptor();
inline const ::std::string& Tablets_Tablet_State_Name(Tablets_Tablet_State value) {
  return ::google::protobuf::internal::NameOfEnum(
    Tablets_Tablet_State_descriptor(), value);
}
inline bool Tablets_Tablet_State_Parse(
    const ::std::string& name, Tablets_Tablet_State* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Tablets_Tablet_State>(
    Tablets_Tablet_State_descriptor(), name, value);
}
// ===================================================================

class Tablets_Tablet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RAMCloud.ProtoBuf.Tablets.Tablet) */ {
 public:
  Tablets_Tablet();
  virtual ~Tablets_Tablet();

  Tablets_Tablet(const Tablets_Tablet& from);

  inline Tablets_Tablet& operator=(const Tablets_Tablet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Tablets_Tablet& default_instance();

  void Swap(Tablets_Tablet* other);

  // implements Message ----------------------------------------------

  inline Tablets_Tablet* New() const { return New(NULL); }

  Tablets_Tablet* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Tablets_Tablet& from);
  void MergeFrom(const Tablets_Tablet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Tablets_Tablet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Tablets_Tablet_State State;
  static const State NORMAL =
    Tablets_Tablet_State_NORMAL;
  static const State RECOVERING =
    Tablets_Tablet_State_RECOVERING;
  static inline bool State_IsValid(int value) {
    return Tablets_Tablet_State_IsValid(value);
  }
  static const State State_MIN =
    Tablets_Tablet_State_State_MIN;
  static const State State_MAX =
    Tablets_Tablet_State_State_MAX;
  static const int State_ARRAYSIZE =
    Tablets_Tablet_State_State_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  State_descriptor() {
    return Tablets_Tablet_State_descriptor();
  }
  static inline const ::std::string& State_Name(State value) {
    return Tablets_Tablet_State_Name(value);
  }
  static inline bool State_Parse(const ::std::string& name,
      State* value) {
    return Tablets_Tablet_State_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required uint64 table_id = 1;
  bool has_table_id() const;
  void clear_table_id();
  static const int kTableIdFieldNumber = 1;
  ::google::protobuf::uint64 table_id() const;
  void set_table_id(::google::protobuf::uint64 value);

  // required uint64 start_key_hash = 2;
  bool has_start_key_hash() const;
  void clear_start_key_hash();
  static const int kStartKeyHashFieldNumber = 2;
  ::google::protobuf::uint64 start_key_hash() const;
  void set_start_key_hash(::google::protobuf::uint64 value);

  // required uint64 end_key_hash = 3;
  bool has_end_key_hash() const;
  void clear_end_key_hash();
  static const int kEndKeyHashFieldNumber = 3;
  ::google::protobuf::uint64 end_key_hash() const;
  void set_end_key_hash(::google::protobuf::uint64 value);

  // required .RAMCloud.ProtoBuf.Tablets.Tablet.State state = 4;
  bool has_state() const;
  void clear_state();
  static const int kStateFieldNumber = 4;
  ::RAMCloud::ProtoBuf::Tablets_Tablet_State state() const;
  void set_state(::RAMCloud::ProtoBuf::Tablets_Tablet_State value);

  // optional fixed64 server_id = 5;
  bool has_server_id() const;
  void clear_server_id();
  static const int kServerIdFieldNumber = 5;
  ::google::protobuf::uint64 server_id() const;
  void set_server_id(::google::protobuf::uint64 value);

  // optional string service_locator = 6;
  bool has_service_locator() const;
  void clear_service_locator();
  static const int kServiceLocatorFieldNumber = 6;
  const ::std::string& service_locator() const;
  void set_service_locator(const ::std::string& value);
  void set_service_locator(const char* value);
  void set_service_locator(const char* value, size_t size);
  ::std::string* mutable_service_locator();
  ::std::string* release_service_locator();
  void set_allocated_service_locator(::std::string* service_locator);

  // optional fixed64 user_data = 7;
  bool has_user_data() const;
  void clear_user_data();
  static const int kUserDataFieldNumber = 7;
  ::google::protobuf::uint64 user_data() const;
  void set_user_data(::google::protobuf::uint64 value);

  // required uint64 ctime_log_head_id = 8;
  bool has_ctime_log_head_id() const;
  void clear_ctime_log_head_id();
  static const int kCtimeLogHeadIdFieldNumber = 8;
  ::google::protobuf::uint64 ctime_log_head_id() const;
  void set_ctime_log_head_id(::google::protobuf::uint64 value);

  // required uint32 ctime_log_head_offset = 9;
  bool has_ctime_log_head_offset() const;
  void clear_ctime_log_head_offset();
  static const int kCtimeLogHeadOffsetFieldNumber = 9;
  ::google::protobuf::uint32 ctime_log_head_offset() const;
  void set_ctime_log_head_offset(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:RAMCloud.ProtoBuf.Tablets.Tablet)
 private:
  inline void set_has_table_id();
  inline void clear_has_table_id();
  inline void set_has_start_key_hash();
  inline void clear_has_start_key_hash();
  inline void set_has_end_key_hash();
  inline void clear_has_end_key_hash();
  inline void set_has_state();
  inline void clear_has_state();
  inline void set_has_server_id();
  inline void clear_has_server_id();
  inline void set_has_service_locator();
  inline void clear_has_service_locator();
  inline void set_has_user_data();
  inline void clear_has_user_data();
  inline void set_has_ctime_log_head_id();
  inline void clear_has_ctime_log_head_id();
  inline void set_has_ctime_log_head_offset();
  inline void clear_has_ctime_log_head_offset();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 table_id_;
  ::google::protobuf::uint64 start_key_hash_;
  ::google::protobuf::uint64 end_key_hash_;
  ::google::protobuf::uint64 server_id_;
  ::google::protobuf::internal::ArenaStringPtr service_locator_;
  int state_;
  ::google::protobuf::uint32 ctime_log_head_offset_;
  ::google::protobuf::uint64 user_data_;
  ::google::protobuf::uint64 ctime_log_head_id_;
  friend void  protobuf_AddDesc_Tablets_2eproto();
  friend void protobuf_AssignDesc_Tablets_2eproto();
  friend void protobuf_ShutdownFile_Tablets_2eproto();

  void InitAsDefaultInstance();
  static Tablets_Tablet* default_instance_;
};
// -------------------------------------------------------------------

class Tablets : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RAMCloud.ProtoBuf.Tablets) */ {
 public:
  Tablets();
  virtual ~Tablets();

  Tablets(const Tablets& from);

  inline Tablets& operator=(const Tablets& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Tablets& default_instance();

  void Swap(Tablets* other);

  // implements Message ----------------------------------------------

  inline Tablets* New() const { return New(NULL); }

  Tablets* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Tablets& from);
  void MergeFrom(const Tablets& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Tablets* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Tablets_Tablet Tablet;

  // accessors -------------------------------------------------------

  // repeated .RAMCloud.ProtoBuf.Tablets.Tablet tablet = 1;
  int tablet_size() const;
  void clear_tablet();
  static const int kTabletFieldNumber = 1;
  const ::RAMCloud::ProtoBuf::Tablets_Tablet& tablet(int index) const;
  ::RAMCloud::ProtoBuf::Tablets_Tablet* mutable_tablet(int index);
  ::RAMCloud::ProtoBuf::Tablets_Tablet* add_tablet();
  ::google::protobuf::RepeatedPtrField< ::RAMCloud::ProtoBuf::Tablets_Tablet >*
      mutable_tablet();
  const ::google::protobuf::RepeatedPtrField< ::RAMCloud::ProtoBuf::Tablets_Tablet >&
      tablet() const;

  // @@protoc_insertion_point(class_scope:RAMCloud.ProtoBuf.Tablets)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::RAMCloud::ProtoBuf::Tablets_Tablet > tablet_;
  friend void  protobuf_AddDesc_Tablets_2eproto();
  friend void protobuf_AssignDesc_Tablets_2eproto();
  friend void protobuf_ShutdownFile_Tablets_2eproto();

  void InitAsDefaultInstance();
  static Tablets* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Tablets_Tablet

// required uint64 table_id = 1;
inline bool Tablets_Tablet::has_table_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Tablets_Tablet::set_has_table_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Tablets_Tablet::clear_has_table_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Tablets_Tablet::clear_table_id() {
  table_id_ = GOOGLE_ULONGLONG(0);
  clear_has_table_id();
}
inline ::google::protobuf::uint64 Tablets_Tablet::table_id() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.Tablets.Tablet.table_id)
  return table_id_;
}
inline void Tablets_Tablet::set_table_id(::google::protobuf::uint64 value) {
  set_has_table_id();
  table_id_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.Tablets.Tablet.table_id)
}

// required uint64 start_key_hash = 2;
inline bool Tablets_Tablet::has_start_key_hash() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Tablets_Tablet::set_has_start_key_hash() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Tablets_Tablet::clear_has_start_key_hash() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Tablets_Tablet::clear_start_key_hash() {
  start_key_hash_ = GOOGLE_ULONGLONG(0);
  clear_has_start_key_hash();
}
inline ::google::protobuf::uint64 Tablets_Tablet::start_key_hash() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.Tablets.Tablet.start_key_hash)
  return start_key_hash_;
}
inline void Tablets_Tablet::set_start_key_hash(::google::protobuf::uint64 value) {
  set_has_start_key_hash();
  start_key_hash_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.Tablets.Tablet.start_key_hash)
}

// required uint64 end_key_hash = 3;
inline bool Tablets_Tablet::has_end_key_hash() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Tablets_Tablet::set_has_end_key_hash() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Tablets_Tablet::clear_has_end_key_hash() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Tablets_Tablet::clear_end_key_hash() {
  end_key_hash_ = GOOGLE_ULONGLONG(0);
  clear_has_end_key_hash();
}
inline ::google::protobuf::uint64 Tablets_Tablet::end_key_hash() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.Tablets.Tablet.end_key_hash)
  return end_key_hash_;
}
inline void Tablets_Tablet::set_end_key_hash(::google::protobuf::uint64 value) {
  set_has_end_key_hash();
  end_key_hash_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.Tablets.Tablet.end_key_hash)
}

// required .RAMCloud.ProtoBuf.Tablets.Tablet.State state = 4;
inline bool Tablets_Tablet::has_state() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Tablets_Tablet::set_has_state() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Tablets_Tablet::clear_has_state() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Tablets_Tablet::clear_state() {
  state_ = 0;
  clear_has_state();
}
inline ::RAMCloud::ProtoBuf::Tablets_Tablet_State Tablets_Tablet::state() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.Tablets.Tablet.state)
  return static_cast< ::RAMCloud::ProtoBuf::Tablets_Tablet_State >(state_);
}
inline void Tablets_Tablet::set_state(::RAMCloud::ProtoBuf::Tablets_Tablet_State value) {
  assert(::RAMCloud::ProtoBuf::Tablets_Tablet_State_IsValid(value));
  set_has_state();
  state_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.Tablets.Tablet.state)
}

// optional fixed64 server_id = 5;
inline bool Tablets_Tablet::has_server_id() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Tablets_Tablet::set_has_server_id() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Tablets_Tablet::clear_has_server_id() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Tablets_Tablet::clear_server_id() {
  server_id_ = GOOGLE_ULONGLONG(0);
  clear_has_server_id();
}
inline ::google::protobuf::uint64 Tablets_Tablet::server_id() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.Tablets.Tablet.server_id)
  return server_id_;
}
inline void Tablets_Tablet::set_server_id(::google::protobuf::uint64 value) {
  set_has_server_id();
  server_id_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.Tablets.Tablet.server_id)
}

// optional string service_locator = 6;
inline bool Tablets_Tablet::has_service_locator() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Tablets_Tablet::set_has_service_locator() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Tablets_Tablet::clear_has_service_locator() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Tablets_Tablet::clear_service_locator() {
  service_locator_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_service_locator();
}
inline const ::std::string& Tablets_Tablet::service_locator() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.Tablets.Tablet.service_locator)
  return service_locator_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Tablets_Tablet::set_service_locator(const ::std::string& value) {
  set_has_service_locator();
  service_locator_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.Tablets.Tablet.service_locator)
}
inline void Tablets_Tablet::set_service_locator(const char* value) {
  set_has_service_locator();
  service_locator_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RAMCloud.ProtoBuf.Tablets.Tablet.service_locator)
}
inline void Tablets_Tablet::set_service_locator(const char* value, size_t size) {
  set_has_service_locator();
  service_locator_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RAMCloud.ProtoBuf.Tablets.Tablet.service_locator)
}
inline ::std::string* Tablets_Tablet::mutable_service_locator() {
  set_has_service_locator();
  // @@protoc_insertion_point(field_mutable:RAMCloud.ProtoBuf.Tablets.Tablet.service_locator)
  return service_locator_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Tablets_Tablet::release_service_locator() {
  // @@protoc_insertion_point(field_release:RAMCloud.ProtoBuf.Tablets.Tablet.service_locator)
  clear_has_service_locator();
  return service_locator_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Tablets_Tablet::set_allocated_service_locator(::std::string* service_locator) {
  if (service_locator != NULL) {
    set_has_service_locator();
  } else {
    clear_has_service_locator();
  }
  service_locator_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), service_locator);
  // @@protoc_insertion_point(field_set_allocated:RAMCloud.ProtoBuf.Tablets.Tablet.service_locator)
}

// optional fixed64 user_data = 7;
inline bool Tablets_Tablet::has_user_data() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Tablets_Tablet::set_has_user_data() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Tablets_Tablet::clear_has_user_data() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Tablets_Tablet::clear_user_data() {
  user_data_ = GOOGLE_ULONGLONG(0);
  clear_has_user_data();
}
inline ::google::protobuf::uint64 Tablets_Tablet::user_data() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.Tablets.Tablet.user_data)
  return user_data_;
}
inline void Tablets_Tablet::set_user_data(::google::protobuf::uint64 value) {
  set_has_user_data();
  user_data_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.Tablets.Tablet.user_data)
}

// required uint64 ctime_log_head_id = 8;
inline bool Tablets_Tablet::has_ctime_log_head_id() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Tablets_Tablet::set_has_ctime_log_head_id() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Tablets_Tablet::clear_has_ctime_log_head_id() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Tablets_Tablet::clear_ctime_log_head_id() {
  ctime_log_head_id_ = GOOGLE_ULONGLONG(0);
  clear_has_ctime_log_head_id();
}
inline ::google::protobuf::uint64 Tablets_Tablet::ctime_log_head_id() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.Tablets.Tablet.ctime_log_head_id)
  return ctime_log_head_id_;
}
inline void Tablets_Tablet::set_ctime_log_head_id(::google::protobuf::uint64 value) {
  set_has_ctime_log_head_id();
  ctime_log_head_id_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.Tablets.Tablet.ctime_log_head_id)
}

// required uint32 ctime_log_head_offset = 9;
inline bool Tablets_Tablet::has_ctime_log_head_offset() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Tablets_Tablet::set_has_ctime_log_head_offset() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Tablets_Tablet::clear_has_ctime_log_head_offset() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Tablets_Tablet::clear_ctime_log_head_offset() {
  ctime_log_head_offset_ = 0u;
  clear_has_ctime_log_head_offset();
}
inline ::google::protobuf::uint32 Tablets_Tablet::ctime_log_head_offset() const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.Tablets.Tablet.ctime_log_head_offset)
  return ctime_log_head_offset_;
}
inline void Tablets_Tablet::set_ctime_log_head_offset(::google::protobuf::uint32 value) {
  set_has_ctime_log_head_offset();
  ctime_log_head_offset_ = value;
  // @@protoc_insertion_point(field_set:RAMCloud.ProtoBuf.Tablets.Tablet.ctime_log_head_offset)
}

// -------------------------------------------------------------------

// Tablets

// repeated .RAMCloud.ProtoBuf.Tablets.Tablet tablet = 1;
inline int Tablets::tablet_size() const {
  return tablet_.size();
}
inline void Tablets::clear_tablet() {
  tablet_.Clear();
}
inline const ::RAMCloud::ProtoBuf::Tablets_Tablet& Tablets::tablet(int index) const {
  // @@protoc_insertion_point(field_get:RAMCloud.ProtoBuf.Tablets.tablet)
  return tablet_.Get(index);
}
inline ::RAMCloud::ProtoBuf::Tablets_Tablet* Tablets::mutable_tablet(int index) {
  // @@protoc_insertion_point(field_mutable:RAMCloud.ProtoBuf.Tablets.tablet)
  return tablet_.Mutable(index);
}
inline ::RAMCloud::ProtoBuf::Tablets_Tablet* Tablets::add_tablet() {
  // @@protoc_insertion_point(field_add:RAMCloud.ProtoBuf.Tablets.tablet)
  return tablet_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::RAMCloud::ProtoBuf::Tablets_Tablet >*
Tablets::mutable_tablet() {
  // @@protoc_insertion_point(field_mutable_list:RAMCloud.ProtoBuf.Tablets.tablet)
  return &tablet_;
}
inline const ::google::protobuf::RepeatedPtrField< ::RAMCloud::ProtoBuf::Tablets_Tablet >&
Tablets::tablet() const {
  // @@protoc_insertion_point(field_list:RAMCloud.ProtoBuf.Tablets.tablet)
  return tablet_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProtoBuf
}  // namespace RAMCloud

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::RAMCloud::ProtoBuf::Tablets_Tablet_State> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::RAMCloud::ProtoBuf::Tablets_Tablet_State>() {
  return ::RAMCloud::ProtoBuf::Tablets_Tablet_State_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Tablets_2eproto__INCLUDED
// RAMCloud pragma [GCCWARN=0]
